# Usa Python come immagine di base
FROM python:3.13

# Imposta la directory di lavoro
WORKDIR /app

# Copia il file client.py nel container
COPY client.py .

# Avvia il client
CMD ["python", "client.py"]
